name: Build and push to dockerhub

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login --username jaynewstrom --password-stdin
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        if: github.event_name == 'push'
      - name: Build
        run: ./build_tag_push.sh ${{ github.event_name == 'push' }}
